#ifndef UI_FILES_H
#define UI_FILES_H

const char* ui_files[] = {
	"/org/siril/ui/filefilters.ui",
	"/org/siril/ui/menus.ui",
	"/org/siril/ui/cosmetic_dialog.ui",
	"/org/siril/ui/binxy_dialog.ui",
	"/org/siril/ui/CLAHE_dialog.ui",
	"/org/siril/ui/cut_dialog.ui",
	"/org/siril/ui/cut_coords_dialog.ui",
	"/org/siril/ui/extract_wavelet_layers_dialog.ui",
	"/org/siril/ui/canon_fixbanding_dialog.ui",
	"/org/siril/ui/Median_dialog.ui",
	"/org/siril/ui/rgradient_dialog.ui",
	"/org/siril/ui/starnet_dialog.ui",
	"/org/siril/ui/wavelets_dialog.ui",
	"/org/siril/ui/asinh_dialog.ui",
	"/org/siril/ui/background_extraction_dialog.ui",
	"/org/siril/ui/savepopup.ui",
	"/org/siril/ui/satu_dialog.ui",
	"/org/siril/ui/SCNR_dialog.ui",
	"/org/siril/ui/bdeconv_dialog.ui",
	"/org/siril/ui/crop_dialog.ui",
	"/org/siril/ui/cut_spectroscopy_dialog.ui",
	"/org/siril/ui/colorchooserdialog.ui",
	"/org/siril/ui/denoise_dialog.ui",
	"/org/siril/ui/extract_channel_dialog.ui",
	"/org/siril/ui/file_information_dialog.ui",
	"/org/siril/ui/composition_dialog.ui",
	"/org/siril/ui/dialog_FFT.ui",
	"/org/siril/ui/dialog_star_remix.ui",
	"/org/siril/ui/linearmatch_dialog.ui",
	"/org/siril/ui/icc_dialog.ui",
	"/org/siril/ui/icc_gamut_dialog.ui",
	"/org/siril/ui/seqlist_dialog.ui",
	"/org/siril/ui/IPS_dialog.ui",
	"/org/siril/ui/StatWindow.ui",
	"/org/siril/ui/stars_list_window.ui",
	"/org/siril/ui/livestacking_player.ui",
	"/org/siril/ui/merge_cfa_dialog.ui",
	"/org/siril/ui/histogram_dialog.ui",
	"/org/siril/ui/pixelmath.ui",
	"/org/siril/ui/resample_dialog.ui",
	"/org/siril/ui/rotation_dialog.ui",
	"/org/siril/ui/script_contents_dialog.ui",
	"/org/siril/ui/split_cfa_dialog.ui",
	"/org/siril/ui/color_calibration.ui",
	"/org/siril/ui/settings_window.ui",
	"/org/siril/ui/siril.ui",
	"/org/siril/ui/data_dialog.ui",
	"/org/siril/ui/aberration_inspector.ui",
	"/org/siril/ui/siril-shortcuts.ui",
// Add entries here as required
// Must be terminated by a NULL string
	""
};

#endif
