.\" Manpage for Siril 1.2
.TH SIRIL "1" "February 2023" "siril 1.2" "User Commands"
.SH NAME
siril \- image processing tool for astronomy and others
.SH SYNOPSIS
Siril GUI
 siril [options] [file]             Start Siril.
  
Siril CLI
 siril-cli [-i conf_file] [-f] [-v] [-c] [-h] [-p] [-d working_directory] [-s script_file] [-r input_pipe_path] [-w output_pipe_path] [image_file_to_open]
.SH DESCRIPTION
\fBSiril\fP is an image processing tool specially tailored for noise reduction and improving the signal/noise ratio of an image from multiple captures, as required in astronomy. It provides powerful tools to align, stack and enhance pictures from various file formats, even image sequences (movies and SER files). It is optimized to run quickly with parallelism, supports all the cameras supported by libraw, and carries out its calculations with a high precision 32-bit floating point engine.
.SH OPTIONS
.IP -i
Starts \fBSiril\fP with the configuration file which path is passed in argument
.IP -f
(or \fB\-\-format\fR) Prints all supported image input formats, depending on the libraries detected at compile-time
.IP -v
(or \fB\-\-version\fR) Prints program name and version and exits
.IP -c
(or \fB\-\-copyright\fR) Prints copyright and exits
.IP -h
(or \fB\-\-help\fR) Short usage help
.IP -p
Starts \fBSiril\fP without the graphical user interface and use the named pipes to accept commands and print logs and status information. On POSIX systems, the named pipes are created in /tmp/siril_commands.in and /tmp/siril_commands.out
.IP -r
(or \fB\-\-inpipe\fR) Provide an alternative path for the input pipe that receives the commands, if \fB\-p\fR is passed. The pipe can be create by an external program with the mkfifo(1) command
.IP -w
(or \fB\-\-outpipe\fR) Provide an alternative path for the output pipe that prints logs and status updates, if \fB\-p\fR is passed. The pipe can be create by an external program with the mkfifo(1) command
.IP -d
(or \fB\-\-directory\fR) Setting the path provided in argument in current working directory
.IP -s
(or \fB\-\-script\fR) Starts \fBSiril\fP without the graphical user interface and run a script instead. Scripts are text files that contain a list of commands to be executed sequentially. In these files, lines starting with a # are considered as comments. If this option is not passed, pipe operation is assumed as if \fB-p\fR had been passed.
.IP image_file_to_open
Open an image or sequence file right after start-up.
.SH FILES
.I ~/.config/siril/siril.cfg
.RS
User preferences. Overridden by the
.B -i
option.
.RE
.I ~/.siril/siril.css
.RS
The style sheet used to change colors of the graphical user interface. This is useful for customization or if a GTK theme is incompatible with some colored elements of \fBSiril\fP.
.SH LINKS
 Website with news, tutorials, FAQ and more: https://www.siril.org/
 Forum: https://discuss.pixls.us/siril
 Command reference and script/pipe operation: https://free-astro.org/index.php?title=Siril:Commands
 Documentation: https://siril.readthedocs.io/en/latest/
 Code and bug reports: https://gitlab.com/free-astro/siril/issues
.SH AUTHOR
 Vincent Hourdin <vh at free-astro.org>
 Cyril Richard <cyril at free-astro.org>
 Cécile Melis <cissou8 at gmail.com>
 Adrian Knagg-Baugh (aje dot baugh plus astro at gmail dot com)
