/*
 * gaia_xp_design.h — externs for the baked Gaia XP design matrices.
 *
 * Definitions live in gaia_xp_design.c, generated by tools/bake_xp_design.py.
 * Layout: gaia_xp_{bp,rp}_design[basis_index * GAIA_XP_NSAMPLES + sample_index].
 */
#ifndef SIRIL_GAIA_XP_DESIGN_H
#define SIRIL_GAIA_XP_DESIGN_H

#ifdef __cplusplus
extern "C" {
#endif

#define GAIA_XP_NBASES   55
#define GAIA_XP_NSAMPLES 343

extern const double gaia_xp_bp_design[GAIA_XP_NBASES * GAIA_XP_NSAMPLES];
extern const double gaia_xp_rp_design[GAIA_XP_NBASES * GAIA_XP_NSAMPLES];
extern const double gaia_xp_bp_merge[GAIA_XP_NSAMPLES];
extern const double gaia_xp_rp_merge[GAIA_XP_NSAMPLES];

#ifdef __cplusplus
}
#endif

#endif
