/*
 * This file is part of Siril, an astronomy image processor.
 * Copyright (C) 2005-2011 Francois Meyer (dulle at free.fr)
 * Copyright (C) 2012-2026 team free-astro (see more in AUTHORS file)
 * Reference site is https://siril.org
 *
 * Siril is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Siril is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Siril. If not, see <http://www.gnu.org/licenses/>.
 *
 * This implementation of multipoint registration & stacking is based on
 * PlanetarySystemStacker by Rolf Hempel:
 *     https://github.com/Rolf-Hempel/PlanetarySystemStacker
 */

/*
 * Binary sidecar (`.mpp`) read/write for an mpp_run_t.
 *
 * Layout (little-endian; explicit byte order — Siril builds for LE
 * platforms but we write/read with explicit serialisation so an LE/BE
 * port doesn't silently corrupt the format):
 *
 *   8 bytes : magic   "SIRILMPP"
 *   uint32  : version (current = 1)
 *   uint32  : flags (reserved; 0)
 *   --- mpp_config_t snapshot ---
 *   sizeof(mpp_config_t) bytes : raw struct (POD)
 *   --- run header ---
 *   int32   : num_frames
 *   int32   : frame_rows
 *   int32   : frame_cols
 *   int32   : num_layers
 *   int32   : bitdepth
 *   int32[4]: patch_yxyx
 *   int32[4]: intersection
 *   int32   : best_frame_idx
 *   int32   : stack_size
 *   int32   : mean_frame_rows
 *   int32   : mean_frame_cols
 *   int32   : aps_count
 *   int32   : aps_dropped_dim
 *   int32   : aps_dropped_structure
 *   uint8   : has_shifts (0 / 1)
 *   --- per-frame arrays (length num_frames each) ---
 *   double[num_frames]                  : quality
 *   double[num_frames]                  : frame_brightness
 *   int32 [num_frames]                  : included
 *   int32 [2 * num_frames]              : global_shifts
 *   --- mean frame ---
 *   int32 [mean_frame_rows*cols]        : mean_frame_data
 *   --- AP records + best_frame_indices ---
 *   mpp_ap_record_t[aps_count]            : raw POD records
 *   int32 [aps_count * selected_per_ap]   : best_frame_indices
 *                                           (v5: selected_per_ap == stack_size)
 *   --- shifts (only if has_shifts == 1) ---
 *   int32                               : shifts.num_frames (= num_frames; sanity)
 *   int32                               : shifts.num_aps    (= aps_count)
 *   double[2 * num_frames * aps_count]  : shifts.shifts
 *   uint8 [    num_frames * aps_count]  : shifts.success
 *   int32                               : shifts.failure_counter
 *
 * Future versions can grow the header / append optional sections after
 * the trailing shifts block, gated on `version`.
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "registration/mpp.h"
#include "registration/mpp/mpp_ap.h"
#include "registration/mpp/mpp_config.h"
#include "registration/mpp/mpp_shift.h"
#include "registration/mpp/mpp_sidecar.h"

#define MPP_SIDECAR_MAGIC   "SIRILMPP"
/* v2: mpp_config_t.drizzle_factor (int) replaced with drizzle_scale
 * (double). Old v1 sidecars need to be regenerated by re-running
 * Analyze; they can't be read in-place because the struct layout
 * shifts the trailing drizzle_mode / pixfrac / kernel fields.
 * v3: appended `int avi_bayer_pattern` to mpp_config_t — only consulted
 * for SEQ_AVI sequences but written unconditionally. Like v2 → v1 the
 * cfg snapshot is raw-bytes, so v3 readers can't accept v2 files.
 * v4: global_shifts widened from int32 to double — feeds Bayer
 * drizzle's cross-frame CFA-phase coverage (see mpp.h:global_shifts
 * comment). Reader promotes v3 in-place: read int32 array, widen to
 * double. Writer always emits v4 doubles.
 * v5: added `bool stack_skip_failed_aps` to mpp_config_t. The cfg
 * snapshot is raw-bytes, so the layout change makes v3/v4 files
 * unreadable — like the v2 → v3 boundary, older sidecars must be
 * regenerated by re-running Analyze / register_mpp.
 * v6: soft per-AP frame selection — two ints appended to the run
 * header (taper, selected_per_ap) and best_frame_indices stored at
 * stride selected_per_ap (= stack_size + taper). The cfg layout is
 * unchanged, so v5 files remain readable: taper = 0,
 * selected_per_ap = stack_size.
 * v7: split per-AP frame selection into register vs stack controls —
 * added `int stack_frame_percent, stack_frame_number` to mpp_config_t
 * (alignment_points_frame_* is now register-only). The raw cfg layout
 * changed, so older sidecars must be regenerated by re-registering. */
#define MPP_SIDECAR_VERSION 7u

static int write_all(FILE *f, const void *p, size_t n) {
	return fwrite(p, 1, n, f) == n ? 0 : -1;
}
static int read_all(FILE *f, void *p, size_t n) {
	return fread(p, 1, n, f) == n ? 0 : -1;
}

mpp_status_t mpp_sidecar_write(const char *path, const mpp_run_t *run) {
	if (!path || !run || !run->aps || !run->cfg) return MPP_EINVAL;

	FILE *f = fopen(path, "wb");
	if (!f) return MPP_EIO;

	if (write_all(f, MPP_SIDECAR_MAGIC, 8) != 0) goto err;
	const uint32_t ver = MPP_SIDECAR_VERSION;
	const uint32_t flags = 0;
	if (write_all(f, &ver, 4) != 0) goto err;
	if (write_all(f, &flags, 4) != 0) goto err;

	/* cfg snapshot. */
	if (write_all(f, run->cfg, sizeof(mpp_config_t)) != 0) goto err;

	/* Run header — list every scalar individually for forward-compat.
	 * The trailing two entries (taper, selected_per_ap) are the v6
	 * additions; selected_per_ap is normalised so the bfi block size
	 * below always matches. */
	const int32_t sel_per_ap = run->selected_per_ap > 0
	    ? run->selected_per_ap : run->stack_size;
	const int32_t h_ints[] = {
		run->num_frames, run->frame_rows, run->frame_cols,
		run->num_layers, run->bitdepth,
		run->patch_yxyx[0], run->patch_yxyx[1],
		run->patch_yxyx[2], run->patch_yxyx[3],
		run->intersection[0], run->intersection[1],
		run->intersection[2], run->intersection[3],
		run->best_frame_idx, run->stack_size,
		run->mean_frame_rows, run->mean_frame_cols,
		run->aps->count, run->aps->dropped_dim, run->aps->dropped_structure,
		run->taper, sel_per_ap,
	};
	if (write_all(f, h_ints, sizeof(h_ints)) != 0) goto err;
	const uint8_t has_shifts = run->shifts ? 1 : 0;
	if (write_all(f, &has_shifts, 1) != 0) goto err;

	const int N = run->num_frames;
	const int M = run->aps->count;
	if (write_all(f, run->quality,          N * sizeof(double)) != 0) goto err;
	if (write_all(f, run->frame_brightness, N * sizeof(double)) != 0) goto err;
	if (write_all(f, run->included,         N * sizeof(int32_t)) != 0) goto err;
	if (write_all(f, run->global_shifts,    2 * N * sizeof(double)) != 0) goto err;
	if (write_all(f, run->mean_frame_data,
	              (size_t) run->mean_frame_rows * run->mean_frame_cols
	              * sizeof(int32_t)) != 0) goto err;
	if (write_all(f, run->aps->records, M * sizeof(mpp_ap_record_t)) != 0) goto err;
	if (write_all(f, run->best_frame_indices,
	              (size_t) M * sel_per_ap * sizeof(int32_t)) != 0) goto err;

	if (has_shifts) {
		const int32_t snf = run->shifts->num_frames;
		const int32_t sna = run->shifts->num_aps;
		if (write_all(f, &snf, 4) != 0) goto err;
		if (write_all(f, &sna, 4) != 0) goto err;
		if (write_all(f, run->shifts->shifts,
		              (size_t) 2 * snf * sna * sizeof(double)) != 0) goto err;
		if (write_all(f, run->shifts->success,
		              (size_t) snf * sna * sizeof(uint8_t)) != 0) goto err;
		const int32_t failures = run->shifts->failure_counter;
		if (write_all(f, &failures, 4) != 0) goto err;
	}

	fclose(f);
	return MPP_OK;
err:
	fclose(f);
	return MPP_EIO;
}

/* Sanity bounds on sizes read from the sidecar. The reader is supposed
 * to be fed a Siril-written file, but a truncated / hand-edited / cross-
 * platform-mangled sidecar can produce huge size fields that would
 * either silently overflow the multiplications below or trigger
 * absurd allocations. Caps are generous (way past any realistic
 * planetary sequence) — they exist to catch corruption, not to
 * constrain real usage. */
#define MPP_SIDECAR_MAX_FRAMES  10000000   /* 10 M frames per sequence */
#define MPP_SIDECAR_MAX_DIM     200000     /* per axis (rows / cols) */
#define MPP_SIDECAR_MAX_APS     10000000   /* APs per run */

mpp_status_t mpp_sidecar_read(const char *path, mpp_run_t **run_out) {
	if (!path || !run_out) return MPP_EINVAL;
	*run_out = NULL;

	FILE *f = fopen(path, "rb");
	if (!f) return MPP_EIO;

	char magic[8];
	if (read_all(f, magic, 8) != 0) goto err;
	if (memcmp(magic, MPP_SIDECAR_MAGIC, 8) != 0) goto err;
	uint32_t ver, flags;
	if (read_all(f, &ver, 4) != 0) goto err;
	if (read_all(f, &flags, 4) != 0) goto err;
	/* mpp_config_t is stored as raw bytes; its layout changed again in v7
	 * (added stack_frame_percent/number), so v5/v6 snapshots no longer
	 * match the struct and only the current version is accepted. Older
	 * sidecars must be regenerated by re-registering. */
	if (ver != MPP_SIDECAR_VERSION) goto err;

	mpp_run_t *run = mpp_run_alloc();
	if (!run) goto err;

	run->cfg = (mpp_config_t *) malloc(sizeof(mpp_config_t));
	if (!run->cfg) { mpp_run_free(run); goto err; }
	if (read_all(f, run->cfg, sizeof(mpp_config_t)) != 0) { mpp_run_free(run); goto err; }

	int32_t h[20];
	if (read_all(f, h, sizeof(h)) != 0) { mpp_run_free(run); goto err; }
	int i = 0;
	run->num_frames        = h[i++];
	run->frame_rows        = h[i++];
	run->frame_cols        = h[i++];
	run->num_layers        = h[i++];
	run->bitdepth          = h[i++];
	for (int j = 0; j < 4; ++j) run->patch_yxyx[j]   = h[i++];
	for (int j = 0; j < 4; ++j) run->intersection[j] = h[i++];
	run->best_frame_idx    = h[i++];
	run->stack_size        = h[i++];
	run->mean_frame_rows   = h[i++];
	run->mean_frame_cols   = h[i++];
	const int aps_count           = h[i++];
	const int aps_dropped_dim     = h[i++];
	const int aps_dropped_structure = h[i++];

	if (ver >= 6u) {
		int32_t h6[2];
		if (read_all(f, h6, sizeof(h6)) != 0) { mpp_run_free(run); goto err; }
		run->taper           = h6[0];
		run->selected_per_ap = h6[1];
	} else {
		run->taper           = 0;
		run->selected_per_ap = run->stack_size;
	}

	/* Bounds-check sizes before any allocation. Reject negative values
	 * (corrupted file) and absurdly large ones that would overflow size_t
	 * in the multiplications below. */
	if (run->num_frames < 1 || run->num_frames > MPP_SIDECAR_MAX_FRAMES
	 || run->mean_frame_rows < 1 || run->mean_frame_rows > MPP_SIDECAR_MAX_DIM
	 || run->mean_frame_cols < 1 || run->mean_frame_cols > MPP_SIDECAR_MAX_DIM
	 || aps_count < 0 || aps_count > MPP_SIDECAR_MAX_APS
	 || run->stack_size < 0 || run->stack_size > run->num_frames
	 || run->taper < 0 || run->taper > run->num_frames
	 || run->selected_per_ap < run->stack_size
	 || run->selected_per_ap > run->num_frames) {
		mpp_run_free(run); goto err;
	}

	uint8_t has_shifts;
	if (read_all(f, &has_shifts, 1) != 0) { mpp_run_free(run); goto err; }

	const int N = run->num_frames;
	run->quality          = (double *)  malloc(N * sizeof(double));
	run->frame_brightness = (double *)  malloc(N * sizeof(double));
	run->included         = (int *)     malloc(N * sizeof(int));
	run->global_shifts    = (double *)  malloc(2 * N * sizeof(double));
	if (!run->quality || !run->frame_brightness
	 || !run->included || !run->global_shifts) { mpp_run_free(run); goto err; }
	if (read_all(f, run->quality,          N * sizeof(double)) != 0
	 || read_all(f, run->frame_brightness, N * sizeof(double)) != 0
	 || read_all(f, run->included,         N * sizeof(int32_t)) != 0) {
		mpp_run_free(run); goto err;
	}
	if (ver == 3u) {
		/* Promote: read int32 pairs, widen to double. */
		int32_t *tmp = (int32_t *) malloc(2 * N * sizeof(int32_t));
		if (!tmp) { mpp_run_free(run); goto err; }
		if (read_all(f, tmp, 2 * N * sizeof(int32_t)) != 0) {
			free(tmp); mpp_run_free(run); goto err;
		}
		for (int i = 0; i < 2 * N; ++i)
			run->global_shifts[i] = (double) tmp[i];
		free(tmp);
	} else {
		if (read_all(f, run->global_shifts, 2 * N * sizeof(double)) != 0) {
			mpp_run_free(run); goto err;
		}
	}

	const size_t mean_count = (size_t) run->mean_frame_rows * run->mean_frame_cols;
	run->mean_frame_data = (int32_t *) malloc(mean_count * sizeof(int32_t));
	if (!run->mean_frame_data) { mpp_run_free(run); goto err; }
	if (read_all(f, run->mean_frame_data, mean_count * sizeof(int32_t)) != 0) {
		mpp_run_free(run); goto err;
	}

	mpp_aps_t *aps = (mpp_aps_t *) calloc(1, sizeof(*aps));
	if (!aps) { mpp_run_free(run); goto err; }
	aps->count = aps_count;
	aps->dropped_dim = aps_dropped_dim;
	aps->dropped_structure = aps_dropped_structure;
	if (aps_count > 0) {
		aps->records = (mpp_ap_record_t *) malloc(aps_count * sizeof(mpp_ap_record_t));
		if (!aps->records) { mpp_ap_free(aps); mpp_run_free(run); goto err; }
		if (read_all(f, aps->records, aps_count * sizeof(mpp_ap_record_t)) != 0) {
			mpp_ap_free(aps); mpp_run_free(run); goto err;
		}
	}
	run->aps = aps;

	const size_t bfi_count = (size_t) aps_count * (size_t) run->selected_per_ap;
	if (bfi_count > 0) {
		run->best_frame_indices = (int *) malloc(bfi_count * sizeof(int32_t));
		if (!run->best_frame_indices) { mpp_run_free(run); goto err; }
		if (read_all(f, run->best_frame_indices,
		             bfi_count * sizeof(int32_t)) != 0) {
			mpp_run_free(run); goto err;
		}
	}

	if (has_shifts) {
		mpp_shifts_t *s = (mpp_shifts_t *) calloc(1, sizeof(*s));
		if (!s) { mpp_run_free(run); goto err; }
		int32_t snf, sna;
		if (read_all(f, &snf, 4) != 0 || read_all(f, &sna, 4) != 0) {
			free(s); mpp_run_free(run); goto err;
		}
		/* The shifts section's snf/sna are encoded only for cross-check;
		 * they must agree with the run header. Anything else is a corrupt
		 * sidecar — reject before allocating. */
		if (snf != run->num_frames || sna != aps_count || snf < 0 || sna < 0) {
			free(s); mpp_run_free(run); goto err;
		}
		s->num_frames = snf;
		s->num_aps    = sna;
		const size_t shifts_count  = (size_t) 2 * (size_t) snf * (size_t) sna;
		const size_t success_count = (size_t)     (size_t) snf * (size_t) sna;
		if (shifts_count > 0) {
			s->shifts = (double *) malloc(shifts_count * sizeof(double));
			if (!s->shifts) { mpp_shift_free(s); mpp_run_free(run); goto err; }
		}
		if (success_count > 0) {
			s->success = (uint8_t *) malloc(success_count * sizeof(uint8_t));
			if (!s->success) { mpp_shift_free(s); mpp_run_free(run); goto err; }
		}
		if ((shifts_count > 0
		     && read_all(f, s->shifts,  shifts_count  * sizeof(double))  != 0)
		 || (success_count > 0
		     && read_all(f, s->success, success_count * sizeof(uint8_t)) != 0)) {
			mpp_shift_free(s); mpp_run_free(run); goto err;
		}
		int32_t failures;
		if (read_all(f, &failures, 4) != 0) {
			mpp_shift_free(s); mpp_run_free(run); goto err;
		}
		s->failure_counter = failures;
		run->shifts = s;
	}

	fclose(f);
	*run_out = run;
	return MPP_OK;
err:
	fclose(f);
	return MPP_EIO;
}

void mpp_sidecar_free(mpp_run_t *run) {
	mpp_run_free(run);
}
