#!/usr/bin/env python3
# Generator for planet_ephem_vsop_data.h — truncated VSOP87A series.
#
# VSOP87A (Bretagnon & Francou 1988): heliocentric rectangular coordinates
# X, Y, Z (AU), referred to the dynamical equinox and ecliptic J2000. Public
# scientific data, freely redistributable. Canonical source (VizieR cat VI/81):
#   https://cdsarc.cds.unistra.fr/ftp/VI/81/VSOP87A.<body>
# (mirror: ftp://ftp.imcce.fr/pub/ephem/planets/vsop87/VSOP87A.<body>)
#
# Each series term contributes  A*cos(B + C*T)  where T = (JDE - 2451545)/365250
# (thousands of Julian years from J2000). The coordinate is
#   sum over power p of  T^p * sum(terms in block (var,p)).
#
# We keep terms with |A| >= THRESHOLD; at 3e-8 the geocentric direction error
# is <= 0.03 arcsec for all bodies — far below the 0.01 deg needed by the
# physical-ephemeris (sub-Earth lat / CM / pole PA) computation.
#
# Usage:  python3 planet_ephem_vsop_gen.py <dir-with-VSOP87A.files> <out.h>
import sys, math

THRESHOLD = 3e-8
BODIES = [("ear", "EARTH"), ("jup", "JUPITER"), ("sat", "SATURN"), ("mar", "MARS")]
COORD = {1: "X", 2: "Y", 3: "Z"}

def parse(path):
    blocks = {}  # (var, power) -> [(A,B,C), ...]
    cur = None
    for line in open(path):
        if "VARIABLE" in line and "TERMS" in line:
            parts = line.split()
            var = int(parts[parts.index("VARIABLE") + 1])
            tt = [p for p in parts if p.startswith("*T**")][0]
            cur = (var, int(tt[4]))
            blocks.setdefault(cur, [])
            continue
        t = line.split()
        if len(t) < 3:
            continue
        blocks[cur].append((float(t[-3]), float(t[-2]), float(t[-1])))
    return blocks

def main():
    srcdir, outpath = sys.argv[1], sys.argv[2]
    out = []
    out.append("/* GENERATED by planet_ephem_vsop_gen.py — DO NOT EDIT. */")
    out.append("/* Truncated VSOP87A (VizieR VI/81), |A|>=%.0e. Heliocentric" % THRESHOLD)
    out.append("   rectangular X,Y,Z (AU), ecliptic & equinox J2000. */")
    out.append("#ifndef SRC_ALGOS_PLANET_EPHEM_VSOP_DATA_H_")
    out.append("#define SRC_ALGOS_PLANET_EPHEM_VSOP_DATA_H_")
    out.append("")
    out.append("typedef struct { double a, b, c; } vsop_term;")
    out.append("typedef struct { const vsop_term *t; int off[7]; } vsop_coord;")
    out.append("typedef struct { vsop_coord c[3]; } vsop_body;")
    out.append("")
    body_inits = []
    for short, name in BODIES:
        blk = parse("%s/VSOP87A.%s" % (srcdir, short))
        coord_inits = []
        for var in (1, 2, 3):
            terms = []
            offs = [0]
            for p in range(6):
                kept = [t for t in blk.get((var, p), []) if abs(t[0]) >= THRESHOLD]
                kept.sort(key=lambda t: -abs(t[0]))
                terms.extend(kept)
                offs.append(len(terms))
            arr = "VSOP_%s_%s" % (short.upper(), COORD[var])
            out.append("static const vsop_term %s[] = {" % arr)
            line = "  "
            for (a, b, c) in terms:
                s = "{%.11g,%.11g,%.11g}," % (a, b, c)
                if len(line) + len(s) > 110:
                    out.append(line)
                    line = "  "
                line += s
            if line.strip():
                out.append(line)
            out.append("};")
            coord_inits.append("{ %s, {%s} }" % (arr, ",".join(str(o) for o in offs)))
        body_inits.append((name, short, coord_inits))
        out.append("")
    for name, short, coord_inits in body_inits:
        out.append("static const vsop_body VSOP_%s = { { %s } };" %
                   (name, ", ".join(coord_inits)))
    out.append("")
    out.append("#endif")
    open(outpath, "w").write("\n".join(out) + "\n")
    # report
    total = sum(1 for l in out if l.strip().startswith("{") or "},{" in l)
    sys.stderr.write("wrote %s (%d lines)\n" % (outpath, len(out)))

if __name__ == "__main__":
    main()
