"""Bake GaiaXPy bp/rp design matrices and merge weights at Siril's 343-pt
2 nm grid into a single C source file: src/algos/gaia_xp_design.c

Re-run only when GaiaXPy or the bp/rp basis CSVs change. Output is
deterministic — diff against the previous version to verify.

Usage:
    python3 tools/bake_xp_design.py [--out PATH] [--config-path GAIAXPY_CONFIG]
"""
import argparse
import datetime
import hashlib
import os
import sys
import textwrap
import numpy as np
from os.path import join, dirname

# Reuse the validated reproduction (sibling module in tools/).
sys.path.insert(0, dirname(__file__))
from numpy_repro import (
    CONFIG_PATH as DEFAULT_CONFIG, SAMPLING, build_design_matrix, merge_weights,
    load_bases, load_dispersion, load_response,
)

DEFAULT_OUT = "src/io/healpix/gaia_xp_design.c"

XPCTS_NBASES = 55
XPSAMPLED_LEN = 343


def file_sha(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        h.update(f.read())
    return h.hexdigest()[:16]


def fmt_double_array(name, arr, ncols=4):
    """Emit a C 'const double name[] = { ... };' with the array values."""
    a = arr.ravel()
    out = [f"const double {name}[{a.size}] = {{"]
    for i in range(0, a.size, ncols):
        chunk = a[i:i + ncols]
        out.append("    " + ", ".join(f"{v:.17e}" for v in chunk) + ",")
    out.append("};\n")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--config-path", default=DEFAULT_CONFIG)
    args = ap.parse_args()

    cfg = args.config_path
    bp_bases_path = join(cfg, "bpC03_v375wi_bases.csv")
    rp_bases_path = join(cfg, "rpC03_v142r_bases.csv")
    bp_disp_path = join(cfg, "bpC03_v375wi_dispersion.csv")
    rp_disp_path = join(cfg, "rpC03_v142r_dispersion.csv")
    bp_resp_path = join(cfg, "bpC03_v375wi_response.csv")
    rp_resp_path = join(cfg, "rpC03_v142r_response.csv")

    bp_bases = load_bases(bp_bases_path)
    rp_bases = load_bases(rp_bases_path)
    bp_disp = load_dispersion(bp_disp_path)
    rp_disp = load_dispersion(rp_disp_path)
    bp_resp = load_response(bp_resp_path)
    rp_resp = load_response(rp_resp_path)
    bp_w, rp_w = merge_weights(SAMPLING)

    bp_d = np.nan_to_num(build_design_matrix(SAMPLING, bp_bases, *bp_disp, *bp_resp, bp_w))
    rp_d = np.nan_to_num(build_design_matrix(SAMPLING, rp_bases, *rp_disp, *rp_resp, rp_w))

    assert bp_d.shape == (XPCTS_NBASES, XPSAMPLED_LEN), bp_d.shape
    assert rp_d.shape == (XPCTS_NBASES, XPSAMPLED_LEN), rp_d.shape
    assert bp_w.shape == (XPSAMPLED_LEN,), bp_w.shape
    assert rp_w.shape == (XPSAMPLED_LEN,), rp_w.shape

    shas = {
        "bp_bases":  file_sha(bp_bases_path),
        "rp_bases":  file_sha(rp_bases_path),
        "bp_disp":   file_sha(bp_disp_path),
        "rp_disp":   file_sha(rp_disp_path),
        "bp_resp":   file_sha(bp_resp_path),
        "rp_resp":   file_sha(rp_resp_path),
    }

    header = textwrap.dedent(f"""\
    /*
     * gaia_xp_design.c — GENERATED by tools/bake_xp_design.py — do not edit by hand.
     *
     * Holds the BP/RP design matrices D[55][343] (flattened row-major) and the
     * merge weights for Siril's xp_sampled grid (336..1020 nm step 2 nm).
     *
     * Source bases: bpC03_v375wi (BP), rpC03_v142r (RP) from GaiaXPy's
     * external-calibration configuration. Re-run the baker if those change.
     *
     * Source-file SHA256 prefixes (regen check):
     *   bp_bases : {shas["bp_bases"]}
     *   rp_bases : {shas["rp_bases"]}
     *   bp_disp  : {shas["bp_disp"]}
     *   rp_disp  : {shas["rp_disp"]}
     *   bp_resp  : {shas["bp_resp"]}
     *   rp_resp  : {shas["rp_resp"]}
     *
     * Layout of design arrays: index = basis_index * {XPSAMPLED_LEN} + sample_index.
     * Samples where the response is zero (e.g. lambda=1020 nm) are baked as 0.0
     * so the runtime needs no edge handling.
     */

    #include "gaia_xp_design.h"

    """)

    body = "\n".join([
        fmt_double_array("gaia_xp_bp_design", bp_d),
        fmt_double_array("gaia_xp_rp_design", rp_d),
        fmt_double_array("gaia_xp_bp_merge", bp_w),
        fmt_double_array("gaia_xp_rp_merge", rp_w),
    ])

    text = header + body

    os.makedirs(dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(text)

    bytes_written = len(text.encode("utf-8"))
    print(f"wrote {args.out}: {bytes_written/1024:.1f} KB source")
    print(f"compiled .rodata: {(bp_d.size + rp_d.size + bp_w.size + rp_w.size) * 8 / 1024:.1f} KB")
    print("source SHA prefixes:")
    for k, v in shas.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
